### ISSUE TITLE
Add Airtime/WiFi Fairness patches?

### ISSUE THREAD

**Issue by bvanderhaar** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#1]
I'm unable to sign up for the LEDE forums, so I'm commenting here..

Any interest in adding the WiFi fairness patches?  They were removed from trunk (http://lists.infradead.org/pipermail/lede-dev/2017-January/005134.html)

I've been running this build for 1.5 months without issue: https://kau.toke.dk/lede/airtime-fairness-builds/ar71xx/generic/.

It looks like there may be some ath10k patches too...

**Comment by bvanderhaar** [comment]
Here's the original ath9k commit - https://github.com/lede-project/source/commit/528f46d0826afa01877ccc7670f2120a7a3b3ea8

**Comment by infinitnet** [comment]
Hey, thank you for your feedback!

I'll definitely consider adding this after doing some research and testing. However, I'm finding more reports of users complaining about issues with ATF patches on LEDE than people suggesting to add them. Maybe it would make sense to wait for LEDE to patch their master branch and opening a bug report with them to share your positive experiences regarding ATF.

**Comment by bvanderhaar** [comment]
Looks like it's in latest trunk now: https://github.com/lede-project/source/commit/764cd09dd845864b0d45c6b1f914b81612a5dd28.

Next build should have the stable version of the ATF if you are building from trunk.

**Comment by infinitnet** [comment]
Yes, I'm building from trunk and just pushed a new build. I'll consider this solved then.
