### ISSUE TITLE
Insufficient space free after install

### ISSUE THREAD

**Issue by pecigonzalo** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#10]
After flashing this image, the device is left with insufficient free disk space, I would suggest disabling some modules that not everyone might use to reduce space.
EG:
- Collectd
- Nano or Vim
- Wger or Curl
- etc

**Comment by infinitnet** [comment]
Did you preserve configs during upgrade? After a fresh installation I still got 4M of free space. Please try the latest release from today.

**Comment by pecigonzalo** [comment]
No I did not. Shouldnt you close the issue after we verify is fix/not valid?

**Comment by pecigonzalo** [comment]
I'll try latest release

**Comment by infinitnet** [comment]
Any update about this and #9 yet?

**Comment by pecigonzalo** [comment]
Will try this afternoon.

**Comment by pecigonzalo** [comment]
Space issue seems much better now, 3.78 MB Free.
