### ISSUE TITLE
Add BBR

### ISSUE THREAD

**Issue by MOZGIII** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#11]
How about adding BBR nework scheduler support?

https://forum.mqmaker.com/t/switch-to-kernel-4-9-20-from-lede-trunk-and-turn-on-tcp-bbr/683

UPD: LEDE upstream is already on 4.9 it seems, so it's just a matter of updating to it and enabling BBR at kernel.

**Comment by infinitnet** [comment]
This will be added with the next release when it's on 4.9.
