### ISSUE TITLE
dnsmasq fail after sysupgrade

### ISSUE THREAD

**Issue by LinuxfarmerHH** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#12]
Just upgraded with 'keep settings' to LEDE Reboot SNAPSHOT r4807-bd24d53ea2. Result was a bugged startup, dnsmasq crashing because of enabled DNSSEC options before. What cause bad effects to access and fix the router.

daemon.crit dnsmasq[32003]: unsupported option (check that dnsmasq was compiled with DHCP/TFTP/DNSSEC/DBus support)

Suggestion: Include dnsmasq-full, so the user can downgrade to smaller versions if required.

**Comment by infinitnet** [comment]
This build now uses `dnsmasq-full`.
