### ISSUE TITLE
Publish all packages

### ISSUE THREAD

**Issue by MOZGIII** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#13]
I need to install some other packages that have kernel modules, but can't use the ones from the standard repo due to package conflicts.
Could you please build and publish all packages to provide the ability to set up custom (local) package repo?

**Comment by infinitnet** [comment]
Sorry, you'd have to compile those yourself. Uploading all packages with each release/nightly will use way too much bandwidth and processing power during compilation. I'm using my workstation for this, not a server.
