### ISSUE TITLE
CPU_CFLAGS_24kc at patches/001-mips-cflag-optimization.patch

### ISSUE THREAD

**Issue by MOZGIII** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#15]
What does patch `patches/001-mips-cflag-optimization.patch` do?
Precisely the part where it redefines `CPU_CFLAGS_24kc` to be `-march=74kc`.
Readme claims this repo should be compatible with openwrt upstream repos (which are `24kc`) and it makes it event weirder to me if this works as intended and things still work.

**Comment by infinitnet** [comment]
That would be a question for gwlim https://github.com/gwlim/mips74k-ar71xx-lede-patch
