### ISSUE TITLE
Slow ingress using SQM + Cake + Piece of cake + bitorrent

### ISSUE THREAD

**Issue by cliobrando** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#16]
Hi,
I'm using SQM + Cake + Piece of cake to reduce bufferbloat. I've used the dslreports speed test to measure my connection speed/bufferbloat and everything is ok (A/A+).
If I open a torrent client with some files that I'm seeding (even if no one is downloading them) the network download speed goes down.
If I run a speed test with the torrent client closed I got a constant download speed of 20Mbit/s. (SQM + Cake + Piece of cake Enabled)
If I open the torrent client, only seeding (6 files), and no one downloading (0 kb/s upload) and run the speed test, I got a variable download rate of 13 - 15Mbits/s  (SQM + Cake + Piece of cake Enabled)
If I open the torrent client, but with SQM + Cake + Piece of cake disabled, I got a constant download speed of 20Mbits/s.
My bittorrent client is qbitorrent, using default settings.

The bitorrent client and the speed tests are executed on different computers.

I don't know if this is the correct behavior, but this thread: https://forum.lede-project.org/t/sqm-and-streaming/6804 seems related.

Thanks!

**Comment by infinitnet** [comment]
This is likely related to the LEDE upstream and not this particular build. Please try the LEDE forums (you already found a related thread) and/or report the bug here https://bugs.lede-project.org/
