### ISSUE TITLE
Update README about Archer C5 v1.20 compatibility

### ISSUE THREAD

**Issue by cescox** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#18]
Hello, the LEDE/OpenWrt wiki point to a full compatibility (apparently same hardware) between Archer C7 v2.0 and Archer C5 v1.20

That mean that this firmware is also compatible with Archer C5 v.10? Anyone tested it? Is it possible to add this information into the README?

**Comment by infinitnet** [comment]
It's probably best to ask in this thread https://forum.lede-project.org/t/gcc-6-3-build-optimized-tp-link-archer-c7-v2-ac1750-lede-firmware/1382 ..

When someone "changed" their C5 to a C7, he'll obviously use C7 images as well, so there really is no need to add this to the readme.
