### ISSUE TITLE
Coming from OpenWRT 15.05.1

### ISSUE THREAD

**Issue by luisfavila** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#2]
Hi!

Congratulations on the project, I have an Archer C7 v2 and was really happy to see a custom built for this great machine!
I'm coming from OpenWRT 15.05.1, should I be able to directly upgrade to your LEDE build?

Thanks!

**Comment by infinitnet** [comment]
Hey,

please note that IPv6 on WAN port isn't properly working with this build atm. But to answer your question, yes, you should be able to move from OpenWRT to this or another LEDE build using the sysupgrade image.
