### ISSUE TITLE
Issue with WAN status "not connected" on boot up

### ISSUE THREAD

**Issue by zapfret** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#20]
When my lede boots up connected to my Comcast cable modem it initially says not connected for the WAN interfaces.  I've tried everything I can think of in the GUI and CLI but only a unplug/plug of the ethernet cable causes the router to run its dhcp pull/ipv6 pull.  

The things I've tried include running a manual enable/disable of the wan interfaces, and restarting services from the command line.

The only thing that seems to bring life to the WAN is to physically disconnect and reconnect the cord on a reboot.

Any ideas?

This has happened with every version of lede I've tried including this amazing optimized version.

**Comment by infinitnet** [comment]
Since this issue seems to be related to the upstream code, please file a bug report at https://bugs.lede-project.org/ and/or open a new thread on LEDE forums. Thanks!
