### ISSUE TITLE
Factory image is not valid to flash via tftp

### ISSUE THREAD

**Issue by akatrevorjay** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#21]
I don't remember the exact thing that causes this as it's been two years since I've touched this router unfortunately, but there's something in the magic that's off that you have to fix. 

Damn I really wish I could remember what the fix for this was now. Maybe you remember? :)

sysupgrade worked just fine by the way.

**Comment by infinitnet** [comment]
No idea either, sorry. Asking on LEDE forums would be your best shot. :)
