### ISSUE TITLE
Will this work for wdr4300/mw4530r? 

### ISSUE THREAD

**Issue by protocold** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#22]
Sorry i am trying to build the binary from gwlim github but however ran into a few problems... 

Therefore I wonder if this patch can be used (how?) on the wdr4300/mw4530r router?

**Comment by infinitnet** [comment]
This is a firmware, not just a patch and it's for the Archer C7. It won't work on other devices except the C5 which uses the same hardware.
