### ISSUE TITLE
OpwnWrt?

### ISSUE THREAD

**Issue by Riadner** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#25]
Why nightly builds now called OpenWrt?

**Comment by crackself** [comment]
it seems lede merge back to openwrt

**Comment by killmoinsneuf** [comment]
Hi,
I confirm : https://forum.lede-project.org/t/announcing-the-openwrt-lede-merge/10217

**Comment by DeadlyMelqn** [comment]
Ahh, thanks for the clarification.
