### ISSUE TITLE
netdev-align patch is only patching a comment.

### ISSUE THREAD

**Issue by MartB** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#29]
https://github.com/infinitnet/lede-ar71xx-optimized-archer-c7-v2/blob/fe82af30f75e2119d102dba4bf927458bbc1aa73/patches/054-netdev-align-NET_SKB_PAD-platform.patch#L14

This entire patch is probably safe to remove.

**Comment by infinitnet** [comment]
Thanks.
