### ISSUE TITLE
Where i can found news releases?

### ISSUE THREAD

**Issue by M2N32** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#33]
Hi Guys, where i can found news releases optimized for archer c7 v2?  my last release is 2017-12-08.

**Comment by infinitnet** [comment]
New release will likely be available today. Also you should switch to nightlies to keep your system up to date instead of relying on releases. I'll only push new releases when something needs to be changed/fixed about my optimizations, but NOT just for LEDEE/package updates.
