### ISSUE TITLE
Last Nightly build was on 6th May

### ISSUE THREAD

**Issue by naeloob** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#36]
Hi, first of all thank you very much for the work on this optimized buildings.

Is there any chance to get the nightly builds start again?
I'm on 4.9.96 Kernel and i need to install a package thar needs newer kernel version.

At the same time i'm starting to try to compile by myself... Will see what happen :)

Thank you in Advance

Regards

**Comment by ghost** [comment]
I'll double that. A lost of packages currently require Kernel version 4.9.102

**Comment by infinitnet** [comment]
New release is likely going to be available today with nightlies fixed as well.
