### ISSUE TITLE
distfeeds.conf mips_74kc not found

### ISSUE THREAD

**Issue by WelterRocks** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#38]
While testing the current nightly build, the distfeeds are inaccessible:

src/gz openwrt_base http://downloads.lede-project.org/snapshots/packages/mips_74kc/base
src/gz openwrt_luci http://downloads.lede-project.org/snapshots/packages/mips_74kc/luci
src/gz openwrt_packages http://downloads.lede-project.org/snapshots/packages/mips_74kc/packages
src/gz openwrt_routing http://downloads.lede-project.org/snapshots/packages/mips_74kc/routing
src/gz openwrt_telephony http://downloads.lede-project.org/snapshots/packages/mips_74kc/telephony

Got 404.

**Comment by infinitnet** [comment]
This was caused by https://github.com/infinitnet/lede-ar71xx-optimized-archer-c7-v2/blob/8b43089b77dcd32b096b16f7871c9273b71093b6/patches/002-mips74kc-set-optimization.patch and just fixed with today's v2 release.
