### ISSUE TITLE
kmod-usb-serial-ftdi and others

### ISSUE THREAD

**Issue by WelterRocks** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#39]
First of all, great work and fast responses, respect!!

Is there a way to get kmod-usb-serial-ftdi in?

Got:
 Downloading http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/packages/kmod-usb-serial-ftdi_4.9.102-1_mips_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-usb-serial-ftdi:
 *      kernel (= 4.9.102-1-74b9e4f13d0eb32a5f2269b23d9bffc9) *         kernel (= 4.9.102-1-74b9e4f13d0eb32a5f2269b23d9bffc9) *
 * opkg_install_cmd: Cannot install package kmod-usb-serial-ftdi.

**Comment by infinitnet** [comment]
This has been answered in #37. There are just too many requests for various kmod packages and if I add them all, the build is going to be completely bloated. You'll just have to compile these packages yourself using the provided configs.
