### ISSUE TITLE
qca_ssdk: Unknown symbol

### ISSUE THREAD

**Issue by infinitnet** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#4]
```
Fri Jun 30 12:15:20 2017 kern.warn kernel: [ 22.623795] qca_ssdk: Unknown symbol ppp_channel_get_protocol (err 0)
Fri Jun 30 12:15:20 2017 kern.warn kernel: [ 22.630500] qca_ssdk: Unknown symbol ppp_is_multilink (err 0)
Fri Jun 30 12:15:20 2017 kern.warn kernel: [ 22.661181] qca_ssdk: Unknown symbol ppp_hold_channels (err 0)
Fri Jun 30 12:15:20 2017 kern.warn kernel: [ 22.667393] qca_ssdk: Unknown symbol ppp_release_channels (err 0)
Fri Jun 30 12:15:20 2017 kern.warn kernel: [ 22.673761] qca_ssdk: Unknown symbol ppp_channel_get_protocol (err 0)
```
Reported by @killmoinsneuf - this one's just for tracking the issue in case somebody else runs into it. Apparently it disappeared after a reboot.

**Comment by killmoinsneuf** [comment]
Hello,
Just to notify : same problem with the nightly today 07/07/2017 "LEDE Reboot SNAPSHOT r4535-4b32d66216 / LuCI Master (git-17.186.70712-4f127c3)" : loop at boot on the following compilation issue 
[   30.877766] qca_ssdk: Unknown symbol ppp_hold_channels (err 0)
[   30.883936] qca_ssdk: Unknown symbol ppp_release_channels (err 0)
[   30.890255] qca_ssdk: Unknown symbol ppp_channel_get_protocol (err 0)
[   30.896906] qca_ssdk: Unknown symbol ppp_is_multilink (err 0)
and the loop trouble disappears after a reboot (soft reboot, today)

**Comment by infinitnet** [comment]
Thanks! Still working after a reboot though, right?

**Comment by killmoinsneuf** [comment]
Yes, indeed ! All works fine after a reboot !
Regards
________________________________
De : Infinitnet <notifications@github.com>
Envoyé : vendredi 7 juillet 2017 17:12:16
À : infinitnet/lede-ar71xx-optimized-archer-c7-v2
Cc : killmoinsneuf; Mention
Objet : Re: [infinitnet/lede-ar71xx-optimized-archer-c7-v2] qca_ssdk: Unknown symbol (#4)


Thanks! Still working after a reboot though, right?

**Comment by infinitnet** [comment]
`qca_ssdk` has been removed for now, because it's useless until we know the commands for hardware NAT. Also with Fast Path we don't really need HWNAT anymore.
