### ISSUE TITLE
documentation correction?

### ISSUE THREAD

**Issue by raskery** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#5]
> Yes. If you don't use PPPoE or another tunneling protocol, you can remove the line option mtu_fix 1 in /etc/config/firewall to squeeze out another 200-30Mbps.

Option mtu_fix 1 does not seem to exist in etc/config/firewall

**Comment by infinitnet** [comment]
I assume you preserved your settings during recent upgrades? This keeps the old configuration. If you do a full wipe, ie. don't preserve settings during upgrade, it should have that option.
