### ISSUE TITLE
Help Me!!!

### ISSUE THREAD

**Issue by bardimnik** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#6]
Hello! Can you make a minimal firmware with the ability to connect and mount usb and enable Hardware Nat for the TP-Link Archer C7 v1? Please.

**Comment by infinitnet** [comment]
Sorry, I only have a V2 and can't possibly test a V1 firmware and I don't have plans on creating a minimal version either. I suggest you use [gwlim's patches](https://github.com/gwlim/mips24k-ar71xx-lede-patch) to compile your own build - it includes hwnat and FP.
