### ISSUE TITLE
Can you add a archer c5 compile?

### ISSUE THREAD

**Issue by ezar** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#7]
Hi,
Can you add a Archer C5 build?

Only add CONFIG_TARGET_DEVICE_ar71xx_generic_DEVICE_archer-c5-v1=y

Regards,

**Comment by ezar** [comment]
Or If you can help me for use your system... 
I use git pull for update lede, after feed update, ... how can apply your patches? an your config?
Regards,

**Comment by ezar** [comment]
Or... upload .config to compare with my config please!

**Comment by infinitnet** [comment]
Hi,

no, sorry, this is only going to be for the C7. You can find the seed config here and use it to generate your config: https://github.com/infinitnet/lede-ar71xx-optimized-archer-c7-v2/blob/master/config.seed

**Comment by ezar** [comment]
Thanks!
Please, Can you share .config instead of config.seed?
Regards
