### ISSUE TITLE
TOP shows high load while IDLE

### ISSUE THREAD

**Issue by pecigonzalo** [infinitnet/lede-ar71xx-optimized-archer-c7-v2#9]
As the message says, with this firmware on TOP shows a really high load while the device is IDLE.

**Comment by digglor** [comment]
Same here, flashed the 2017-08-09 release and notice a 50% cpu load when idle. Using the stock LEDE firmware i have 0-5% CPU load when idle. I did a sysupgrade from the latest stock LEDE.

**Comment by pecigonzalo** [comment]
It is a little bit better if I sysupgrade from LEDE

**Comment by infinitnet** [comment]
Could you try today's release please and also make sure you reboot and wait 5-10mins after it's up and running?

**Comment by infinitnet** [comment]
PS. I just upgraded to today's build and even with all preinstalled service active and *without* a reboot after the upgrade it utilizes just between 2 and 3% CPU when idle. If you're getting different results, please try upgrading without preserving your settings (just download a backup before you upgrade) and see if that resolves the issue.

**Comment by digglor** [comment]
I did a sysupgrade with the latest build yesterday but noticed the same 50%+ CPU load even after 10 minutes. I will try a clean flash at a later time to see if it fixes the load.

**Comment by pecigonzalo** [comment]
CPU Load still high.
Im getting constant 0.4 to 0.8 with almost no traffic.

**Comment by infinitnet** [comment]
```
root@r00ter:~# uptime
 13:52:04 up 2 days, 17 min,  load average: 0.02, 0.02, 0.00
```

This is my C7 v2 running the latest release. Please to a clean sysupgrade (don't preserve settings) if you experience issues. This amount of load definitely isn't default behaviour of this firmware.

**Comment by pecigonzalo** [comment]
I never do sysupgrade, I dont even backup and restore, so that is not the problem. Lets see if @digglor can confirm this issue or not.

**Comment by infinitnet** [comment]
This was related to a certain package that has been removed in the latest release. Please try 2017-11-06.
